[package]
name = "yakui-macroquad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yakui-miniquad = { path = "../yakui-miniquad"}
macroquad = { version = "0.3.24", default-features = false }
